swagger: "2.0"
info:
  description: "Placeholder for the desscription of this thing."
  version: "0.0.1"
  title: "Tracker 2 JIRA"
  termsOfService: "https://github.com/king-jam/tracker2jira/blob/master/docs/TOS.md"
  contact:
    email: "james.r.king4@gmail.com"
  license:
    name: "Mozilla Public License 2.0"
    url: "https://www.mozilla.org/en-US/MPL/2.0/"
basePath: "/t2j"
tags:
- name: "general"
  description: "General Application Settings & Information"
  externalDocs:
    description: "Documentation"
    url: "https://github.com/king-jam/tracker2jira/blob/master/docs/README.md"
- name: "projects"
  description: "Project configurations that are under management"
- name: "users"
  description: "Operations about project members"
schemes:
- "http"
- "https"
paths:
  # The general base routes
  /:
    get:
      tags:
      - "general"
      summary: "Returns the default home page"
      operationId: "root"
      responses:
        200:
          description: "The default home page for the application"
  /version:
    get:
      tags:
      - "general"
      summary: "Returns the current version running."
      operationId: "version"
      responses:
        200:
          description: "The current version of the service"
  /login:
    post:
      tags:
      - "general"
      summary: "Logs in and returns authentication type based on parameters"
      description: ""
      operationId: "login"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "loginRequest"
        required: true
        description: "A JSON obect containing the login and password"
        schema:
          $ref: "#/definitions/LoginRequest"
      responses:
        200:
          description: "Successful Login"
        400:
          description: "Invalid username/password"
  #/logout: #stubbed out for now
  /config:
    get:
      tags:
      - "general"
      summary: "Get the current running configuration"
      responses:
        200:
          description: "The current configuration"
    patch:
      tags:
      - "general"
      summary: "Update the current running configuration"
      responses:
        200:
          description: "Configuration Changed"
#  /projects/tracker:
#    get:
#    post:
#    put:
#    delete:
#  /projects/jira:
#    get:
#    post:
#    put:
#    delete:
#  /users:
#    get:
#    post:
#  /users/{user}:
#    get:
#    post:
#    patch:
#    put:
#    delete:

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: "#/definitions/Error"
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Error"
definitions:
  LoginRequest:
    description: "Login Request Body"
    type: "object"
    properties:
      name:
        type: "string"
      password:
        type: "string"
  # Schema for error response body
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
